services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./dist/angular-refresh-token:/usr/share/nginx/html
      - ./nginx_certificates:/etc/nginx/ssl
    environment:
      # for production
      # - BACKEND_URL=http://geokiosk.ru/api/
      # for development
      - BACKEND_URL=http://192.168.70.220:8888
      - GEOSERVER_URL=http://geoserver.usgik.ru:9090
